image: node:8.4.0

before_script:
  - npm config -s set //registry.npmjs.org/:_authToken=$NPM_TOKEN
  - yarn

test:
  stage: test
  script: yarn test
  coverage: /^All files\s+\|\s+(\d+(?:\.\d+)*).+/
